1:Przepelnienie pamieci operacyjnej.
2:Brak nazwy.
3:Niezadeklarowana nazwa.
4:Powt¢rzenie tej samej nazwy.
5:Niedopuszczalny znak; sprawdz, czy nie pominales symbolu ko¤ca. napisu lub komentarza.
6:Bledna stala typu rzeczywistego.
7:Bledna stala typu calkowitego.
8:Brak symbolu ' ko¤czacego napis.
9:Niedopuszczalne spietrzenie wstawek tekstowych.
10:Niedoko¤czony tekst zr¢dlowy.
11:Zbyt dluga linia.
12:Brak nazwy typu.
13:Zbyt wiele otwartych plik¢w.
14:Brak pliku o podanej nazwie.
15:Nie znaleziono pliku dyskowego.
16:Przepelnienie dysku.
17:Bledna, lub niewlasciwie umieszczona dyrektywa.
18:Tlumaczenie wymaga uzycia zbyt wielu plik¢w.
19:Brak deklaracji typu wskazywanego w definicji typu wskaznikowego.
20:Brak nazwy zmiennej.
21:Niewlasciwy symbol na poczatku definicji typu.
22:Zdefiniowanie zbyt "duzego" typu.
23:Elementy X typu podstawowego nie spelniaja warunk¢w typu zbiorowego.
24:Typ skladowy typu plikowego zawiera typ plikowy.
25:Liczba znak¢w w typie napisowym nie jest typu 1..255.
26:Niezgodnosc typ¢w.
27:Niewlasciwy typ granicy w typie okrojonm.
28:W typie okrojonym granica dolna przekracza granice g¢rna.
29:Brak typu porzadkowego.
30:Brak stalej calkowitej.
31:Brak stalej.
32:Brak stalej calkowitej lub rzeczywistej.
33:Brak nazwy typu.
34:Niedopuszczalny typ wartosci funkcji.
35:Brak nazwy etykiety.
36:Brak symbolu BEGIN.
37:Brak symbolu END.
38:Brak wyrazenia typu calkowitego.
39:Brak wyrazenia typu porzadkowego.
40:Brak wyrazenia logicznego.
41:Typ argumentu niezgodny z operatorem.
42:Niedopuszczalny symbol w wyrazeniu.
43:Nazwa funkcji poza tresciz funkcji.
44:Brak nazwy pola rekordu.
45:Plik *.obj wiekszy niz 64 KB.
46:Plik *.obj niezgodny z konstekstem symbolu EXTERNAL.
47:Blad w pliku *.obj.
48:Kod programu lub pakietu przekracza 64 KB.
49:Segment danych przekracza 65520 B.
50:Brak symbolu DO.
51:Niedopuszczalna postac pliku *.obj.
52:Niedopuszczalna postac pliku *.obj.
53:Niedopuszczalna postac pliku *.obj.
54:Brak symbolu OF.
55:Brak symbolu INTERFACE.
56:Niedopuszczalna postac pliku *.obj.
57:Brak symbolu THEN.
58:Brak symbolu TO lub DOWNTO.
59:Brak zapowiedzianej deklaracji.
60:Zbyt wiele deklaracji podprogram¢w.
61:Niedopuszczalna konwersja typu.
62:Dzielenie przez zero.
63:Niewlasciwy rodzaj pliku.
64:Niewlasciwy typ parametru.
65:Brak zmiennej typu wskaznikowego.
66:Brak zmiennej typu napisowego.
67:Brak wyrazenia typu napisowego.
68:Brak deklaracji uzycia pakietu.
69:Nazwa pakietu niezgodna z deklaracja uzycia.
70:Nieaktualny modul wynikowy.
71:Powt¢rzona nazwa pakietu.
72:Bledny plik *.tpu.
73:Brak symbolu IMPLEMENTATION.
74:Etykieta niezgodna z typem selektora.
75:Brak zmiennej o strukturze rekordu.
76:Stala porzadkowa spoza przedzialu.
77:Brak zmiennej plikowej.
78:Brak wyrazenia typu wskaznikowego.
79:Brak wyrazenia arytmetycznego.
80:Instrukcja skoku poza blok.
81:Etykieta uzycia powt¢rnie przed inna instrukcja.
82:Brak instrukcji z zadeklarowana etykieta.
83:Bledny argument operatora adresowego @.
84:Brak symbolu UNIT.
85:Brak symbolu ';'.
86:Brak symbolu ':'.
87:Brak symbolu ','.
88:Brak symbolu '('.
89:Brak symbolu ')'.
90:Brak symbolu '='.
91:Brak symbolu ':='.
92:Brak symbolu '['.
93:Brak symbolu ']'.
94:Brak symbolu '.'.
95:Brak symbolu '..'.
96:Za malo pamieci na zmienne.
97:Niewlasciwa zmienna w instrukcji FOR.
98:Brak zmiennej calkowitej.
99:Pr¢ba nadanie wartosci poczatkowej zmiennej plikowej.
100:Zla dlugosc stalej napisowej.
101:Zla kolejnosc p¢l rekordu.
102:Brak stalej napisowej.
103:Brak zmiennej typu calkowitego lub rzeczywistego.
104:Brak zmiennej typu porzadkowego.
105:Blednie uzyty operator < w INLINE.
106:Brak wyrazenia typu znakowego.
107:Program wynikowy zbyt skomplikowany.
108:Za malo pamieci.
109:Nie mozna odnalezc potrzebnego pliku *.exe.
110:Pr¢ba uruchomienia pakietu.
111:Wcisnieto Control-Break.
112:Zla stala wyboru w instrukcji CASE.
113:Niedopuszczalny symbol na poczatku instrukcji.
114:Pr¢ba wywolania procedury INTERRUPT.
115:Nie ma koprocesora.
116:Konstrukcja ta moze zostac skompilowana tylko przy uzyciu koprocesora 8087.
117:Nie odnaleziono adresu wynikowego.
118:Dolaczenie zbior¢w nie jest dozwolone w tym miejscu.
120:Spodziewane slowo NIL.
121:Bledny desygnator.
122:Bledne odwolanie do zmiennej.
123:Zbyt wiele nazw symbolicznych.
124:Za dluga czesc wykonawcza.
126:Pliki musza byc parametrami przekazywanymi przez zmienna.
127:Zbyt wiele warunkowych nazw symbolicznych.
128:Opuszczono dyrektywe kompilatora IF.
129:Opuszczono dyrektywe kompilatora ENDIF.
130:Bledne warunkowe nazwy symboliczne.
131:Nieodpowiedniosc nagl¢wka z poprzednia definicja.
132:Powazny blad zwiazany z dyskiem(np: naped nie jest zamkniety).
133:Obliczenie wyrazenia stalego lub podanego w oienku Watch nie jest mozliwe.
